/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YV5LxuqYWzh
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { GithubIcon, TwitchIcon } from "lucide-react";
import Link from "next/link";
import { AnilistIcon, DiscordIcon } from "../icons/socials";
import Logo from "../icons/logo";
import { socials } from "@/metadata";

export function Footer() {
  return (
    <footer className="m-10 grid grid-cols-1 items-start gap-y-8 bg-card text-card-foreground md:grid-cols-3 md:gap-x-8 md:px-10">
      <div className="flex flex-col items-center space-y-6">
        <Logo
          // alt="Artrix"

          height="100"
          style={{
            aspectRatio: "200/100",
            objectFit: "cover",
            fill: "currentcolor",
          }}
          width="200"
        />
        <div className="flex space-x-4">
          <Link href={`https://discord.com/users/${socials.DISCORD_ID}`}>
            <DiscordIcon className="h-6 w-6 " />
          </Link>
          <Link href={`https://github.com/${socials.GITHUB_TAG}`}>
            <GithubIcon className="h-6 w-6 " />
          </Link>
          <Link href={`https://twitch.tv/${socials.ANILIST_USERNAME}`}>
            <TwitchIcon className="h-6 w-6" />
          </Link>
          <Link href={`https://anilist.co/user/${socials.TWITCH_USERNAME}`}>
            <AnilistIcon className="h-6 w-6" />
          </Link>
        </div>
      </div>
      <div className="flex flex-col space-y-2">
        <h3 className="font-bold">Company</h3>
        <Link className=" " href="#">
          About us
        </Link>
        <Link className=" " href="#">
          Our team
        </Link>
        <Link className=" " href="#">
          Careers
        </Link>
      </div>
      <div className="flex flex-col space-y-2">
        <h3 className="font-bold">Help</h3>
        <Link className=" " href="#">
          Support
        </Link>
        <Link className=" " href="#">
          FAQs
        </Link>
        <Link className=" " href="#">
          Contact us
        </Link>
      </div>
      <div className="col-span-1 mt-6 text-center md:col-span-3">
        <p className="text-sm">
          &#169; {new Date().getFullYear()} Artrix. All rights reserved.
        </p>
      </div>
    </footer>
  );
}
