"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YV5LxuqYWzh
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { GithubIcon, MoonIcon, SunIcon, TwitchIcon } from "lucide-react";
import Link from "next/link";
import { AnilistIcon, DiscordIcon } from "../icons/socials";
import Logo, { LogoText } from "../icons/logo";

import { Switch } from "@nextui-org/switch";
import { useTheme } from "next-themes";
import { Button } from "../ui/button";
import { socials } from "@/metadata";
import { useToast } from "@/components/ui/use-toast";

export function Footer() {
  const { setTheme, theme, systemTheme } = useTheme();
  const { toast } = useToast();
  return (
    <footer className="m-10 grid grid-cols-1 items-start gap-y-8 bg-card text-card-foreground md:grid-cols-3 md:gap-x-8 md:px-10">
      <div className="flex flex-col items-center space-y-6">
        <LogoText
          // alt="Artrix"

          height="100"
          style={{
            aspectRatio: "200/100",
            objectFit: "cover",
            fill: "currentcolor",
          }}
          width="200"
        />
        <div className="flex space-x-4">
          <button
            onMouseDown={async () => {
              await navigator.clipboard.writeText(socials.DISCORD_TAG);
              toast({ title: "Copied discord tag!" });
            }}
          >
            <DiscordIcon className="h-6 w-6 " />
          </button>
          <Link href={`https://github.com/${socials.GITHUB_TAG}`}>
            <GithubIcon className="h-6 w-6 " />
          </Link>
          <Link href={`https://twitch.tv/${socials.ANILIST_USERNAME}`}>
            <TwitchIcon className="h-6 w-6" />
          </Link>
          <Link href={`https://anilist.co/user/${socials.TWITCH_USERNAME}`}>
            <AnilistIcon className="h-6 w-6" />
          </Link>
        </div>
        <div className="grid grid-flow-col place-items-center gap-2">
          <Switch
            classNames={{
              thumb: "bg-background",
              // base: "!bg-foreground",
              endContent: "fill-background stroke-background",
              wrapper: "!bg-foreground !ring-ring ",
            }}
            checked={theme === "dark"}
            startContent={<SunIcon />}
            endContent={<MoonIcon />}
            onValueChange={(c) => setTheme(c ? "dark" : "light")}
            id="theme-toggle"
          />
        </div>
      </div>
      <div className="flex flex-col space-y-2">
        <h3 className="font-bold">Company</h3>
        <Link className=" " href="#">
          About us
        </Link>
        <Link className=" " href="#">
          Our team
        </Link>
        <Link className=" " href="#">
          Careers
        </Link>
      </div>
      <div className="flex flex-col space-y-2">
        <h3 className="font-bold">Help</h3>
        <Link className=" " href="#">
          Support
        </Link>
        <Link className=" " href="#">
          FAQs
        </Link>
        <Link className=" " href="#">
          Contact us
        </Link>
      </div>
      <div className="col-span-1 mt-6 text-center md:col-span-3">
        <p className="text-sm">
          &#169; {new Date().getFullYear()} Artrix. All rights reserved.
        </p>
        <p className="text-sm">
          Made with love by{" "}
          <a href={`https://github.com/${socials.GITHUB_TAG}`}>
            <Button className="font-bold" variant="link">
              <span>@Artrix</span>
            </Button>
          </a>
          using{" "}
          <a href={`https://tailwindcss.com/`}>
            <Button className="font-bold" variant="link">
              Tailwind
            </Button>{" "}
          </a>
          &
          <a href={`https://nextjs.org/`}>
            <Button className="font-bold" variant="link">
              Next.js
            </Button>
          </a>
        </p>
      </div>
    </footer>
  );
}
